---
title: "Generate Acoustic Study"
output: html_document
date: "2025-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## PAMpal Data Processing

Start by loading the required packages

```{r, load packages, message=FALSE}
library("easypackages")
library("lubridate")
libraries("PAMpal","PAMmisc","dplyr",  "here",'beepr')
here()
```

1.  Define details of deployment to process

    ```{r, Set deployment metadata}
    ###USER-DEFINED FIELDS####
    baseDir <- 'E:/Analysis/'  
    DriftID<-'ADRIFT_012'
    binFolder <- paste0(baseDir,'Binaries/',DriftID)    #Folder with binaries
    # this database should be a COPY of the original because we will add events to it later
    db <- paste0(baseDir,'Databases/',DriftID,' - Copy.sqlite3')

    pps <- PAMpalSettings(db=db, 
                          binaries = binFolder,
                          sr_hz='auto', 
                          winLen_sec=.0025, 
                          filterfrom_khz=10, 
                          filterto_khz=80)

    #Import known Risso's dolphin Event Times
    GgTimes<-read.csv(here('EventTimes','ADRIFT_GgDetections.csv'))
    GgTimes$start<-as.POSIXct(GgTimes$UTC,format='%Y-%m-%d %H:%M:%S',tz='UTC')

    #Define end time. For CCES, this will be 2 minutes after file start time
    GgTimes$end<-as.POSIXct(GgTimes$end,format='%Y-%m-%d %H:%M:%S',tz='UTC')
    DriftTimes<-filter(GgTimes,DriftName==DriftID)
    DriftTimes$id<-paste0(DriftID,'_',seq(1:nrow(DriftTimes)))

    if(substr(DriftID,1,4)=='CCES'){
      DriftTimes$end<-DriftTimes$start + seconds(119) }
    ```

2.  **Set up our PPS** (PAMPal Settings Object) for the deployment

```{r, Process click detections}
#Use event times from CSV file
data <- processPgDetections(pps, mode='time',grouping=DriftTimes,
                            format='%m/%d/%y %H:%M',species='Gg',id=DriftID)

#save original acoustic study (before cleaning)
saveRDS(data, paste0(baseDir,'AcousticStudies/',DriftID,'_Gg.rds'))
beep()
```
