---
title: "03_Identify_Peaks"
output: html_document
date: "2025-08-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We are following general methods of Soldevilla et al 2017 "Geographic Variation in Risso's dolphin echolocation click spectra".

We use Pamguard to detect echolocation clicks, then use PamPal to generate acoustic studies, and add events to the Pamguard databases.

False click detections are removed manually by identifying the click waveform, bearing, and wigner plot in Pamguard Click Display.

\***We should confirm that manual cleaning is necessary**.

From Soldevilla et al 2017: "To minimize the influence of high-frequency energy loss with distance, and remove hydrophone-system-specific features, the click spectrum frequency range was truncated to 19 to 50kHz and cepstral-filtering methods (described below) were applied. ....

While spectrum truncation and cepstral-filtering methods minimize these effects on the spectra, the inclusion of many clicks from random orientations ensures the suite of variability expected in wild dolphin recordings is accounted for, leading to more robust results"

## Cepstral-Filtering

1.  Truncate and normalize spectra (19-50 kHz)

2.  Calculate real cepstrum of clicks

3.  High-pass lifter each click spectra (transform the truncated spectrum to its cepstrum using the discrete cosign transform (DCT) and multiply the cepstrum by a rectangular window function filter in which the first six quefrencies were zero and all other quefrencies were one.

4.  Apply an inverse DCT to the liftered signal to return them to the spectral domain

## Identify spectral peaks 
